import type { WorkItemDetail } from "./types";
import { fmtDate } from "./dates";

/**
 * Build a self-contained, AI-ready task brief (markdown) from a work item and
 * its structured spec — the "spec-first" promise made concrete: everything an
 * agent (or engineer) needs to execute, in one copyable packet.
 */
export function buildAgentBrief(item: WorkItemDetail): string {
  const lines: string[] = [];
  const spec = item.spec;

  lines.push(`# ${item.key}: ${item.title}`, "");

  const meta: string[] = [`**Type:** ${item.type}`, `**Priority:** ${item.priority}`, `**Stage:** ${item.stage.name}`];
  if (item.assignee) meta.push(`**Assignee:** ${item.assignee.name}`);
  if (item.epic) meta.push(`**Epic:** ${item.epic.title}`);
  if (item.estimate != null) meta.push(`**Estimate:** ${item.estimate} pts`);
  if (item.startDate || item.dueDate) {
    meta.push(`**Schedule:** ${fmtDate(item.startDate) || "—"} → ${fmtDate(item.dueDate) || "—"}`);
  }
  if (item.labels.length) meta.push(`**Labels:** ${item.labels.map((l) => l.name).join(", ")}`);
  lines.push(meta.join("  \n"), "");

  if (item.description) {
    lines.push("## Summary", item.description, "");
  }

  if (spec) {
    lines.push(`_Spec status: ${spec.status}_`, "");
    const section = (title: string, body: string) => {
      if (body.trim()) lines.push(`## ${title}`, body.trim(), "");
    };
    section("Problem & Context", spec.problem);
    section("Goals", spec.goals);
    section("Non-Goals", spec.nonGoals);
    section("Technical Approach", spec.approach);
    section("Risks & Open Questions", spec.risks);

    if (spec.criteria.length) {
      lines.push("## Acceptance Criteria");
      for (const c of spec.criteria) lines.push(`- [${c.done ? "x" : " "}] ${c.text}`);
      lines.push("");
    }
    if (spec.tests.length) {
      lines.push("## Test Plan");
      for (const t of spec.tests) lines.push(`- (${t.status}) ${t.text}`);
      lines.push("");
    }
  } else {
    lines.push("_No structured spec yet — add one for a stronger brief._", "");
  }

  lines.push("---", `Generated by Swish from ${item.key}.`);
  return lines.join("\n");
}
